The ``lazy_matrix_mul`` module
==========================
Using ``lazy_matrix_mul``
--------------------------
>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
[[ 7 10]
 [15 22]]
>>> print(lazy_matrix_mul([[1, 2]], [[3, 3], [4, 4]]))
[[11 11]]
>>> print(lazy_matrix_mul([[1, 2, 3]], [[4], [5], [6]]))
[[32]]
>>> print(lazy_matrix_mul([[1, 2, 3, 4]], [[1], [2]]))
Traceback (most recent call last):
...
ValueError: shapes (1,4) and (2,1) not aligned: 4 (dim 1) != 2 (dim 0)
>>> print(lazy_matrix_mul({1, 4, 5}, [[1]]))
Traceback (most recent call last):
...
TypeError: Object arrays are not currently supported
>>> print(lazy_matrix_mul([[1]], [1, 3, 4]))
Traceback (most recent call last):
...
ValueError: shapes (1,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)
>>> print(lazy_matrix_mul([[1, 2, 3], [4, 5], [6, 7, 8]], [[0,0,0], [0,0,0], [0,0,0]]))
Traceback (most recent call last):
...
ValueError: setting an array element with a sequence.
>>> print(lazy_matrix_mul([], [[1]]))
Traceback (most recent call last):
...
ValueError: shapes (0,) and (1,1) not aligned: 0 (dim 0) != 1 (dim 0)
>>> print(lazy_matrix_mul([1, 2, 3], [[1]]))
Traceback (most recent call last):
...
ValueError: shapes (3,) and (1,1) not aligned: 3 (dim 0) != 1 (dim 0)
>>> print(lazy_matrix_mul())
Traceback (most recent call last):
...
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
>>> print(lazy_matrix_mul([[1]]))
Traceback (most recent call last):
...
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'
>>> print(lazy_matrix_mul([[1]], [[]]))
[]
>>> print(lazy_matrix_mul([[1, 2, 3], [4, 5, 6]], [[1, 2], [3, "s"], [5, "seis"]]))
Traceback (most recent call last):
...
TypeError: invalid data type for einsum
>>> print(lazy_matrix_mul([[1]], [1, 2, 3]))
Traceback (most recent call last):
...
ValueError: shapes (1,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)
>>> print(lazy_matrix_mul([[1, 2, "tre"]], [[1], [2], [2]]))
Traceback (most recent call last):
...
TypeError: invalid data type for einsum
>>> print(lazy_matrix_mul([[1]], [[1, 2], [3], [4, 5]]))
Traceback (most recent call last):
...
ValueError: setting an array element with a sequence.
